# Generated by Django 5.0.2 on 2024-02-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fts1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='paragraph',
            new_name='input',
        ),
    ]
